### ISSUE TITLE
support xcworkspace 

### ISSUE THREAD

**Issue by tami5** [xbase-lab/xbase#86]
Please comment below if you need support for xcworkspace and why

**Comment by smolck** [comment]
I'd like support for this, specifically so I can work with projects that use [Cocoapods](https://cocoapods.org). With that, once you set up everything and run `pod install` for a project, a `.xcworkspace` file is generated which you always use instead of the `.xcodeproj` one.

**Comment by smolck** [comment]
> hey @smolck, glad to see you using xbase :D

Haven't quite figured out how to set it up yet, but it's a really cool project that I'm definitely interested in :) I've been getting really sick of Xcode.

> if I understood correctly, xcodeproj has everything you need to build and run xcodeproj, regardless of xcworkspace. I never use pod, so I'm not quite sure. but with XcodeGen, so far I haven't needed xcworkspace.

With cocoapods, the .xcworkspace file that's generated you use instead because it has all of the pods set up/included in the project so you can use them. If I open one of my project's xcodeproj instead of the generated xcworkspace from `pod install`, it won't build because of that, since as far as it's concerned the pods aren't available/don't exist.

I could probably create a minimal project that uses cocoapods if you want something to test with, just lmk.

> In last pr marge I started appending -project {}.xcodeproj, would switching to -workspace {}.xcworkspace (that is if it exists), would result in same behavior? i.e. I can still append configuration/target ..etc. If so I don't mind checking and prioritizing xcworkspace over xcodeproj.

I'm not familiar with what's going on here, so I'm not sure? But it seems like that would work? If you want to create a PR doing this and @ me on it, I'm happy to try it out (assuming I get xbase set up properly).

**Comment by EastHell** [comment]
Looks like the only thing that stop me from using xbase atm, because all of my current project using them.

**Comment by tami5** [comment]
awesome thanks @smolck, I wonder if might as well just offer first class support for cocoa based projects, like with tuist and xcodegen (expect the xcodegen generate part). So when the user edit pod file it would recompile the project

**Comment by smolck** [comment]
I mean if it's not that much code to support it, then I'm not sure there's any real harm in doing so.
